### ISSUE TITLE
 Error: Cannot find module /tutorial-part-one/gatsby-config.js

### ISSUE THREAD

**Issue by DenisaKusnirova** [gatsbyjs/gatsby-starter-hello-world#11]
Hello, after installing gatsby-cli

`npm install --global gatsby-cli`

and running

`gatsby new tutorial-part-one https://github.com/gatsbyjs/gatsby-starter-hello-world`

followed by

```
cd tutorial-part-one
gatsby develop
```
I get an error
```

We encountered an error while trying to load your site's gatsby-config.js.
  Error: Cannot find module '/Users/deniskakusnirova/Documents/PORTFOLIO/tutorial-part-one/gatsby-config.js'
  
  - v8-compile-cache.js:159 require
    [tutorial-part-one]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - get-config-file.js:36 _callee$
    [tutorial-part-one]/[gatsby]/dist/bootstrap/get-config-file.js:36:28
  
  - get-config-file.js:81 getConfigFile
    [tutorial-part-one]/[gatsby]/dist/bootstrap/get-config-file.js:81:17
  
  - index.js:103 _callee$
    [tutorial-part-one]/[gatsby]/dist/bootstrap/index.js:103:34
```
I'm using Node v8.9.3, npm v5.5.1
Can anyone help me with this issue please?

**Comment by KyleAMathews** [comment]
Sorry about this! It might be because you're on an older version of Gatsby? Could you copy your package.json here so I can look at it?

**Comment by DenisaKusnirova** [comment]
I did not change anything. There is a default package.json in the repo. I tried running other starter projects and those work without any issues, so I just modified a gatsby-example-site project and went from there.

**Comment by DenisaKusnirova** [comment]
Sure, here it is:

```
{
  "name": "gatsby-starter-hello-world",
  "description": "Gatsby hello world starter",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "gatsby": "^1.9.207",
    "gatsby-link": "^1.6.37"
  }
}
```

**Comment by KyleAMathews** [comment]
Can you try running `npm upgrade` and then `gatsby develop` again to see if the site works with the latest version of Gatsby?

**Comment by DenisaKusnirova** [comment]
This is what I'm getting now:

 ```
Error: Unable to find plugin "gatsby-source-filesystem"
  
  - load-plugins.js:144 resolvePlugin
    [tutorial-part-one]/[gatsby]/dist/bootstrap/load-plugins.js:144:11
  
  - load-plugins.js:193 processPlugin
    [tutorial-part-one]/[gatsby]/dist/bootstrap/load-plugins.js:193:27
  
  - load-plugins.js:214 
    [tutorial-part-one]/[gatsby]/dist/bootstrap/load-plugins.js:214:28
  
  - Array.forEach
  
  - load-plugins.js:213 _callee$
    [tutorial-part-one]/[gatsby]/dist/bootstrap/load-plugins.js:213:28
  
  - index.js:117 _callee$
    [tutorial-part-one]/[gatsby]/dist/bootstrap/index.js:117:20
  
  - next_tick.js:131 _combinedTickCallback
    internal/process/next_tick.js:131:7
```
```

{
  "name": "gatsby-starter-hello-world",
  "description": "Gatsby hello world starter",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "gatsby": "^1.9.216",
    "gatsby-link": "^1.6.37"
  }
}
```

**Comment by KyleAMathews** [comment]
Looks like you added `gatsby-source-filesystem` to your gatsby-config.js?

Can you reproduce the problem if you start from scratch with a new hello-world site?

**Comment by abyabrkal** [comment]
I got similar errors while using this repo.
My Node@8.11.3 and npm@6.4.1

I uninstalled yarn _via brew uninstall yarn_.
I reinstalled the repo again via gatsby new command and it worked fine.

**Comment by marcobiedermann** [comment]
@abyabrkal So maybe you got an old version of the `gatsby-cli` globally installed on your machine.

**Comment by abyabrkal** [comment]
@marcobiedermann I uninstalled v1 and installed v2 while checking out v2 tutorials.
I got the issue while trying out tutorial-part-two
My gatsby version@2.0.0-rc.5

**Comment by mikelax** [comment]
@abyabrkal  can you post the `package.json` contents along with the output of `gatsby info`

I just tested this starter repo with both `1.1.58` and `2.4.2` of the gatsby-cli package and both worked. 

I think this issue can be closed now.

**Comment by anthonybrown** [comment]
I can confirm everything is working fine now.

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.67
    Firefox: 61.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.0 => 2.0.28
    gatsby-source-filesystem: ^2.0.1-rc.6 => 2.0.1-rc.6
    gatsby-transformer-remark: ^2.1.1-rc.5 => 2.1.1-rc.5
  npmGlobalPackages:
    gatsby-cli: 2.4.3
    gatsby: 2.0.0-rc.28
```
