### ISSUE TITLE
Contents of 'static' directory not copied to build output

### ISSUE THREAD

**Issue by krugarmatt** [gatsbyjs/gatsby-starter-hello-world#21]
I'm new to Gatsby so I followed the tutorial on gatsbyjs.org to get started, but I noticed that when building this starter template from its default state, the contents of the '**src/static**' directory isn't copied to the build output directory (**public**) as it is described in the documentation.

### Steps to replicate:
1. Run steps 1-3 of the '**Create a Gatsby site**' section of the tutorial ([https://www.gatsbyjs.org/tutorial/part-zero/#create-a-site](https://www.gatsbyjs.org/tutorial/part-zero/#create-a-site)).
2. Run `gatsby build` to generate the output.
3. Inspect the contents of the '**public**' directory. Notice that the '**favicon.ico**' file hasn't been copied from '**src/static**'.

It seems the way to resolve this issue is to move the '**src/static**' directory into the root of the project before building. When you run `gatsby build` after doing so, the '**favicon.ico**' file is correctly copied into the root of the '**public**' output directory.

### Steps to resolve:
1. Run steps 1-3 of the '**Create a Gatsby site**' section of the tutorial ([https://www.gatsbyjs.org/tutorial/part-zero/#create-a-site](https://www.gatsbyjs.org/tutorial/part-zero/#create-a-site))
2. Move the '**src/static**' directory into the root of the project.
3. Run `gatsby build` to generate the output.
3. Inspect the contents of the '**public**' directory. Notice that this time the '**favicon.ico**' file has been copied from '**src/static**'.

**Comment by hexrcs** [comment]
Created PR #23 

[According to the docs](https://www.gatsbyjs.org/docs/adding-images-fonts-files/#using-the-static-folder), the static folder should be placed directly under the project root.

BTW @krugarmatt if you would like to further customize favicon etc, be sure to check out [`gatsby-plugin-manifest`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-manifest) 😃

**Comment by KyleAMathews** [comment]
Fixed, thanks @hexrcs!
