### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by codejet** [gatsbyjs/gatsby-starter-hello-world#5]
I tried going through your tutorial which uses this starter. When running `gatsby develop` I got the following error:

```
There was an error compiling the html.js component for the development server.

Error: Module build failed: Error: Couldn't find preset "react" relative to directory "path/to/folder"
```

I already deleted node_modules and ran `yarn` but no luck.

Only thing I thought was weird is the path in the error message. It's not the folder created by running `gatsby new` but the one above (and on top of that I guess it should be looking inside node_modules).

**Comment by KyleAMathews** [comment]
If you use other starters do you have the same problem?

**Comment by codejet** [comment]
Yes, I tried Lumen the day before and it worked (at least after downgrading yarn -  https://github.com/alxshelepenok/gatsby-starter-lumen/issues/41).

**Comment by codejet** [comment]
I figured it out: in the folder where i have all my projects, including the gatsby tutorial, there was a .babelrc present for some reason and this caused the error.
