### ISSUE TITLE
gatsby build wont finish - stuck on createPagesStatefully

### ISSUE THREAD

**Issue by jordanoverbye** [gatsbyjs/gatsby-starter-hello-world#8]
I've created a new site by running `gatsby new gatsby-site https://github.com/gatsbyjs/gatsby-starter-hello-world`.

I haven't made any changes to the code and running `gatsby develop` works. But when I try `gatsby build` it gets stuck at `createPagesStatefully`

```success delete html files from previous builds — 0.014 s
success open and validate gatsby-config.js — 0.006 s
success copy gatsby files — 0.033 s
success onPreBootstrap — 0.008 s
success source and transform nodes — 0.031 s
success building schema — 0.192 s
success createLayouts — 0.010 s
success createPages — 0.003 s
⠐ createPagesStatefully

**Comment by KyleAMathews** [comment]
Sorry about that! A PR broke it yesterday. Just merged and published a fix https://github.com/gatsbyjs/gatsby/pull/3827
